apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-28cf-t22gs
    machine.openshift.io/cluster-api-machine-role: workerocs
    machine.openshift.io/cluster-api-machine-type: workerocs
  name: cluster-28cf-t22gs-workerocs-us-east-2b
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-28cf-t22gs
      machine.openshift.io/cluster-api-machineset: cluster-28cf-t22gs-workerocs-us-east-2b
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-28cf-t22gs
        machine.openshift.io/cluster-api-machine-role: workerocs
        machine.openshift.io/cluster-api-machine-type: workerocs
        machine.openshift.io/cluster-api-machineset: cluster-28cf-t22gs-workerocs-us-east-2b
    spec:
      metadata:
        creationTimestamp: null
        labels:
          role: storage-node
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
            id: ami-0eef624367320ec26
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          - ebs:
              iops: 0
              volumeSize: 100
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-28cf-t22gs-worker-profile
          instanceType: m5d.large
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-28cf-t22gs-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-28cf-t22gs-private-us-east-2b
          tags:
          - name: kubernetes.io/cluster/cluster-28cf-t22gs
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""
