apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: netproj-template

parameters:
- name: NAMESPACE
  displayName: Namespace
  description: Namespace to deploy objects
  required: true

objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      name: "${NAMESPACE}"
    name: "${NAMESPACE}"

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ose
    labels:
      run: ose
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: ose
    template:
      metadata:
        labels:
          run: ose
      spec:
        containers:
          - name: ose
            image: registry.access.redhat.com/ubi9/ubi:latest
            command: ["bash", "-c", "python3 -m http.server 5000"]
            ports:
            - containerPort: 5000
              protocol: TCP
            readinessProbe:
              tcpSocket:
                port: 5000
              periodSeconds: 10
              failureThreshold: 3
            livenessProbe:
              tcpSocket:
                port: 5000
              initialDelaySeconds: 5
              periodSeconds: 10
              failureThreshold: 3
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
