## Environment Overview

You will be interacting with an OpenShift 4 cluster that is running on {{
ENVIRONMENT }}. During the lab you will also install OpenShift Container
Storage, based on Rook/Ceph.

The basics of the OpenShift 4 installation have been completed in advance.
The OpenShift cluster is essentially set to all defaults and looks like the
following:

* 3 master nodes
* 3 worker nodes
* 1 bastion host

link:https://github.com/openshift-labs/workshop-dashboard[Homeroom] is a solution that provides an integrated lab guide, terminal, and console environment. It is running inside the cluster that you will be interacting with.

## Conventions
You will see various code and command blocks throughout these exercises. Some of
the command blocks can be executed directly. Others will require modification
of the command before execution. If you see a command block with a red border
(see below), the command will copy to clipboard for slight required modification.

The icon beside the command blocks should tell you if the commands will be executed or copied.

- This command block will be copied to your clipboard for modification.

[source,none,role="copypaste copypaste-warning"]
----
some command to modify
----
[NOTE]
====
To paste the copied command try the following

- Cmd + V _tested to work in Chrome on macOS_
- Ctrl + Shift + V _tested to work in Chrome and Firefox on Windows 10_
- Right click in the terminal window _tested to work on Edge on Windows 10_
====
- This will execute in the console

[source,none,role="execute"]
----
echo Hello World\!
----

Most command blocks support auto highlighting or executing with a click. If you hover over
the command block above and left-click, it should automatically highlight all the
text to make for easier copying. Look at the symbol next to the block to see if it will copy or execute.

### Cloning content
We have prepared various YAML files and other artifacts that you will use for
the exercises in advance. You will need to clone these artifacts onto your
bastion host now. Please execute the following:

[source,bash,role="execute"]
----
git clone https://github.com/openshift/openshift-cns-testdrive.git -b ocp4-prod content
----

[WARNING]
====
kubeadmin is required in the majority of following exercises
====
##### Log-in as kubeadmin for future exercises

[source,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

Future exercises will refer to `{{ HOME_PATH }}/content/support`.
