= 4.2 - Create a Default Project Template

In this part of the lab, we will create a project request template. The API server automatically provisions projects based on the template that is identified by the `projectRequestTemplate` parameter of the master-config.yaml file.

Let us go step by step to first create a project request template and then add the objects 'quota and limit ranges' to the project in the 'default' namespace. 

== 1) Start with the current default project template:

To create your own custom project template use the 'oc adm' tool and by using this a template file in YAML format will be created which can be then modified. Type the following command in the terminal -

 $ oc adm create-bootstrap-project-template 
 
NOTE:  This step just displays how a template would look, but this won't be used as we are providing you with a modified project-request template in this lab.

== 2) Modify the template to add quota and limit ranges :

NOTE: You will not have to edit the template because we will be providing a modified template , but make note of the format and fields shown below so that you could edit your own template next time.

Type the cat command to view the contents of the template.yaml file provided -

 $ cat /home/cloud-user/template.yaml
 
[literal]
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: ${PROJECT_NAME}-quota
  spec:
    hard:
      pods: "10"
      limits.cpu: "1"
      limits.memory: "1Gi"
      resourcequotas: 1
      requests.storage: "5Gi"
      persistentvolumeclaims: "5"
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: ${PROJECT_NAME}-limits
    creationTimestamp: null
  spec:
    limits:
      - 
        type: Container
        max:
          cpu: 5
          memory: "1Gi"
        min:
          cpu: 100m
          memory: "5Mi"
        default:
          cpu: 4
          memory: "1024Mi"
        defaultRequest:
          cpu: 100m
          memory: "512Mi"
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${PROJECT_NAME}
  userNames: null
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER

The sections to be considered would be 'ResourceQuota' and 'LimitRange'.

=== A) ResourceQuota -

"A resource quota, defined by a ResourceQuota object, provides constraints that limit aggregate resource consumption per project. It can limit the quantity of objects that can be created in a project by type, as well as the total amount of compute resources and storage that may be consumed by resources in that project." 

[literal]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: ${PROJECT_NAME}-quota
  spec:
    hard:
      pods: "10"
      limits.cpu: "1"
      limits.memory: "1Gi"
      resourcequotas: 1
      requests.storage: "5Gi"
      persistentvolumeclaims: "5"
      
[lowerroman, start=1]
. `kind: ResourceQuota` - This specifies that the object to be created is a quota.
. `name: ${PROJECT_NAME}-quota` - Here you can provide the name of the quota.
. `pods: "10"` - 	The total number of pods in a non-terminal state that can exist in the project.
. `limits.cpu: "1"` - Across all pods in a non-terminal state, the sum of CPU limits cannot exceed 1 core.
. ` limits.memory: "1Gi"` - Across all pods in a non-terminal state, the sum of memory limits cannot exceed 1Gi.
. `resourcequotas: 1` - The total number of resource quotas that can exist in the project.
. `requests.storage: "5Gi" ` - Across all persistent volume claims in a project, the sum of storage requested cannot exceed this value.
. `persistentvolumeclaims: "5"` - 	The total number of persistent volume claims in a project.


=== B) LimitRanges - 
"A limit range, defined by a LimitRange object, enumerates compute resource constraints in a project at the pod, container, image, image stream, and persistent volume claim level, and specifies the amount of resources that a pod, container, image, image stream, or persistent volume claim can consume."

We have provided the example of 'container' level resource constraints in this template.

[literal]
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: ${PROJECT_NAME}-limits
    creationTimestamp: null
  spec:
    limits:
      - 
        type: Container
        max:
          cpu: 5
          memory: "1Gi"
        min:
          cpu: 100m
          memory: "5Mi"
        default:
          cpu: 4
          memory: "1024Mi"
        defaultRequest:
          cpu: 100m
          memory: "512Mi"
	  
Some rules must have kept in mind while defining the `max` and `min` limits for the conatiner.

. If the configuration defines a min CPU, then the request value must be greater than the CPU value. A limit value does not need to be specified.
. If the configuration defines a max CPU, then you do not need to define a request value, but a limit value does need to be set that satisfies the maximum CPU constraint.
. 
== 3) Create the project-request template in the namespace 'default' :

 $ oc create -f template.yaml -n default
 
Output would look like -
 
[literal]
[cloud-user@master ~]$  oc create -f template.yaml -n default
template "project-request" created

== 4) Modify the master-config.yaml file to reference the loaded template :

[literal]
...
projectConfig:
  projectRequestTemplate: "default/project-request"
  ...

== 5) Restart the service :
Use the following command to restart the atomic-openshift-master.service so that the new changes will be now applied to any projects further created by using 'oc new-project'.

 # systemctl restart atomic-openshift-master
 
== 6) Test that new project is created and it has quota and limits :

 $ oc new-project first-project
 
 $ oc describe project first-project 

Output should be like :-

[literal]
[cloud-user@master ~]$ oc describe project first-project
Name:		first-project
Namespace:	<none>
Created:	29 seconds ago
Labels:		<none>
Annotations:	openshift.io/description=
		openshift.io/display-name=
		openshift.io/requester=system:admin
		openshift.io/sa.scc.mcs=s0:c8,c7
		openshift.io/sa.scc.supplemental-groups=1000070000/10000
		openshift.io/sa.scc.uid-range=1000070000/10000
Display Name:	<none>
Description:	<none>
Status:		Active
Node Selector:	<none>
Quota:
	Name:			first-project-quota
	Resource		Used	Hard
	--------		----	----
	limits.cpu		0	1
	limits.memory		0	1Gi
	persistentvolumeclaims	0	5
	pods			0	10
	requests.storage	0	5Gi
	resourcequotas		1	1
Resource limits:
	Name:		first-project-limits
	Type		Resource	Min	Max	Default
	----		--------	---	---	---
	Container	cpu		100m	5	4
	Container	memory		5Mi	1Gi	1Gi


