## Environment Overview

You will be interacting with an OpenShift 4 cluster that is running on {{
ENVIRONMENT }}. During the lab you will also install OpenShift Container
Storage, based on Rook/Ceph.

The basics of the OpenShift 4 installation have been completed in advance.
The OpenShift cluster is essentially set to all defaults and looks like the
following:

* 3 master nodes
* 3 worker nodes
* 1 bastion host

You will now SSH into the bastion host in order to access the environment and
complete the rest of the exercises.

## Conventions
You will see various code and command blocks throughout these exercises. Some of
the command blocks can be copy/pasted directly. Others will require modification
of the command before execution. If you see a command block with a red border
(see below), the command will require slight modification.

[source,none,role="copypaste copypaste-warning"]
----
some command to modify
----

Most command blocks support auto highlighting with a click. If you hover over
the command block above and left-click, it should automatically highlight all the
text to make for easier copying.

[NOTE]
====
Logging in is required in order to continue the following exercises
====
### Logging in
The bastion host on which this lab guide is running is currently configured
with an SSH key that is also present on the machine where you are sitting.
You can simply SSH to the bastion host like so:

[source,bash,role="execute"]
----
ssh -l lab-user {{ BASTION_FQDN }}
----

The `lab-user` account has password-less sudo privileges. You'll notice that
there is a 4-digit alphanumeric string (eg: f4a3) in the hostname. This
string is your `GUID`. Since you will often use `GUID`, it makes sense to
export it as an environment variable:

[source,bash,role="execute"]
----
export GUID=`hostname | cut -d. -f2`
----

### Cloning content
We have prepared various YAML files and other artifacts that you will use for
the exercises in advance. You will need to clone these artifacts onto your
bastion host now. Please execute the following:

[source,bash,role="execute"]
----
cd
git clone https://github.com/openshift/openshift-cns-testdrive.git -b ocp4-prod content
----

Future exercises will refer to `/home/lab-user/content/support`.