## Environment Overview

You will be interacting with an OpenShift 4 cluster that is running on {{ ENVIRONMENT }}. During the lab you will also install OpenShift Container
Storage, based on Rook/Ceph.

The basics of the OpenShift 4 installation have been completed in advanced.
The OpenShift cluster is essentially set to all defaults and looks like the
following:

* 3 master nodes
* 3 worker nodes

Additionally, this lab guide is being hosted on an EC2 instance that you will
now SSH into in order to access the environment and complete the rest of the
exercises.

## Conventions
You will see various code and command blocks throughout these exercises. Some of
the command blocks can be copy/pasted directly. Others will require modification
of the command before execution. If you see a command block with a red border
(see below), the command will require slight modification.

[source,none,role="copypaste copypaste-warning"]
----
some command to modify
----

Most command blocks support auto highlighting with a click. If you hover over
the command block above and left-click, it should automatically highlight all the
text to make for easier copying.

### Logging in
The bastion host on which this lab guide is running is currently configured
with an SSH key that is also present on the machine where you are sitting.
You can simply SSH to the bastion host like so:

[source,bash,role="copypaste"]
----
ssh -l lab-user {{ BASTION_FQDN }}
----

The `lab-user` account has password-less sudo privileges. You'll notice that
there is a 4-digit alphanumeric string (eg: f4a3) in the hostname. This
string is your `GUID`. Since you will often use GUID, it makes sense to
export it as an environment variable:

[source,bash,role="copypaste"]
----
export GUID=`hostname | cut -d. -f2`
----
