## Environment Overview

You will be interacting with an OpenShift 4 cluster that is running on {{
ENVIRONMENT }}. During the lab you will also install OpenShift Container
Storage, based on Rook/Ceph.

The basics of the OpenShift 4 installation have been completed in advance.
The OpenShift cluster is essentially set to all defaults and looks like the
following:

* 3 master nodes
* 3 worker nodes
* 1 bastion host

## Conventions
You will see various code and command blocks throughout these exercises. Some of
the command blocks can be copy/pasted directly. Others will require modification
of the command before execution. If you see a command block with a red border
(see below), the command will require slight modification.

[source,none,role="copypaste copypaste-warning"]
----
some command to modify
----

Most command blocks support auto highlighting or executing with a click. If you hover over
the command block above and left-click, it should automatically highlight all the
text to make for easier copying. Look at the symbol next to the block to see if it will copy or execute.

### Cloning content
We have prepared various YAML files and other artifacts that you will use for
the exercises in advance. You will need to clone these artifacts onto your
bastion host now. Please execute the following:

[source,bash,role="execute"]
----
git clone https://github.com/kaovilai/openshift-cns-testdrive.git -b ocp4-prod content
----

[WARNING]
====
kubeadmin is required in the majority of following exercises
====
##### Log-in as kubeadmin for future exercises
[source,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

Future exercises will refer to `/opt/app-root/src/content/support`.