## Environment Overview

You will be interacting with an OpenShift 3.9 cluster that is running on {{
ENVIRONMENT }}. During the lab you will also install Container-Native Storage
3.9. The complete environment consists of the following systems:

* 1 master node
* 1 infrastructure node
* 6 "application" nodes
** 3 will run workload and the initial Container Native Storage instances
** 3 will be added to the cluster later
* 1 server running Red Hat Identity Management (IdM, for LDAP authentication)

.Lab Environment Overview
[options="header"]
|==============================================
| Role     | Internal FQDN
| Master Node       | {{MASTER_INTERNAL_FQDN}}
| Infrastructure Node        | {{INFRA_INTERNAL_FQDN}}
| Application Node #1        | {{NODE1_INTERNAL_FQDN}}
| Application Node #2        | {{NODE2_INTERNAL_FQDN}}
| Application Node #3        | {{NODE3_INTERNAL_FQDN}}
| Application Node #4        | {{NODE4_INTERNAL_FQDN}}
| Application Node #5        | {{NODE5_INTERNAL_FQDN}}
| Application Node #6        | {{NODE6_INTERNAL_FQDN}}
| IdM Server     |    {{IDM_INTERNAL_FQDN}}
|==============================================

All addresses are internal to the lab environment. The only system you
publicly access via SSH and the browser is the OpenShift Master node:

.Public Lab Access
[options="header"]
|==============================================
| Role     | Public FQDN
| Master Node       | {{MASTER_EXTERNAL_FQDN}}
|==============================================

You will be installing OpenShift Container Platform v3.9 using the advanced
installation method, which involves executing various Ansible playbooks. You
will also install Container Native Storage v3.9.

Note that references to product documentation will be specifically pointing
to the 3.9 versions, but newer software and documentation versions may be
available.

## How to get support

In case of technical or functional problems please reach out to mailto:openshift-ops-testdrive@redhat.com[openshift-ops-testdrive@redhat.com]. This is a ticket based system where you will be able to reach the authors and supporters of this Test Drive Experience.

## Conventions
You will see various code and command blocks throughout these exercises. Some of
the command blocks can be copy/pasted directly. Others will require modification
of the command before execution. If you see a command block with a red border
(see below), the command will require slight modification.

[source,none,role=copypaste]
----
some command to modify
----

### Logging in
You will only need to SSH into the master node to perform all of these
exercises. If you are on Linux or Mac, use the on-board SSH client.

[NOTE]
====
Windows users are encouraged to use the
link:https://www.chiark.greenend.org.uk/~sgtatham/putty/[PuTTY] client.
Instructions for how to use SSH keys with PuTTY can be found in their
link:https://the.earth.li/~sgtatham/putty/0.70/htmldoc/Chapter8.html#pubkey[documentation].
====

Log on to the master node as `cloud-user` and the password `{{ KEYNAME }}`

[source,bash]
----
ssh -l cloud-user {{MASTER_EXTERNAL_FQDN}}
----

Once you are logged in you end up on the OpenShift Master Node:

----
[cloud-user@master ~]$
----

The `cloud-user` account has password-less sudo privileges and SSH login on
all systems using internal addressing from the table above.
