## Environment Overview

You will be interacting with an OpenShift environment that is running on {{ ENVIRONMENT }}. The environment consists of the following systems:

* 1 master node
* 1 infrastructure node
* 6 "application" nodes
** 3 will run workload and the initial Container Native Storage instances
** 3 will be added to the cluster later
* 1 server running Red Hat Identity Management (IdM, for LDAP authentication)

.Lab Environment Overview
[options="header"]
|==============================================
| Role     | Public FQDN | Internal FQDN
| Master Node     | {{MASTER_EXTERNAL_FQDN}}  | {{MASTER_INTERNAL_FQDN}}
| Infrastructure Node     |   | {{INFRA_INTERNAL_FQDN}}
| Application Node #1     |   | {{NODE1_INTERNAL_FQDN}}
| Application Node #2     |   | {{NODE2_INTERNAL_FQDN}}
| Application Node #3     |   | {{NODE3_INTERNAL_FQDN}}
| Application Node #4     |   | {{NODE4_INTERNAL_FQDN}}
| Application Node #5     |   | {{NODE5_INTERNAL_FQDN}}
| Application Node #6     |   | {{NODE6_INTERNAL_FQDN}}
| IdM Server     |   | {{IDM_INTERNAL_FQDN}}
|==============================================

You will be installing OpenShift Container Platform v3.5 using the advanced
installation method, driven by Ansible playbooks. You will also install
Container Native Storage.

You will only need to SSH into the master node to perform all of these
exercises. However, should you wish to explore the other hosts in the
environment, the naming convention is as follows:

If you are on Linux or macOS use the the private key (*PEM* file) you downloaded earlier. Make sure it has the right permissions to be used by the SSH client:

  chmod 0400 ~/Downloads/<pem-file-name>

Log on to the master node as `cloud-user`:

  ssh -i ~/Downloads/<pem-file-name> -l cloud-user {{MASTER_EXTERNAL_FQDN}}

The `cloud-user` account has password-less sudo privileges and SSH login on all systems using internal addressing from the table above.

## Conventions

You will see various code and command blocks throughout these exercises. Some of
the command blocks can be copy/pasted directly. Others will require modification
of the command before execution. If you see a command block with a red border
(see below), the command will require slight modification.

[source,role=copypaste]
----
some command to modify
----
