## Installation and Verification

There are two primary methods of installation for OpenShift Container Platform.

* Quick Installation
The quick installation provides a simplified experience through an interactive
CLI. It does not support as much customization or configuration of the OpenShift
environment. For quick and simple POC-type scenarios, it can be a useful tool.

* Advanced Installation
You will use the advanced installation method in this exercise. The advanced
installation method involves configuring an Ansible hosts file and then invoking
Ansible directly to run the installation playbooks. The advanced installer
supports many, many configuration and customization options.

We have pre-configured the installer's configuration file (`/etc/ansible/hosts`)
for you.

For more information on installing OpenShift Container Platform, please refer to
the
link:https://docs.openshift.com/container-platform/3.5/install_config/install/quick_install.html[installation
section] of the product documentation.

### Examining the provided Ansible inventory file
First, let's examine the provided installer configuration file.

#### SSH into `master`
Hopefully you downloaded the SSH private key before you opened the labguide. If
not, make sure that you return to the Qwiklabs page to get the private key.
Don't forget where you put it, and don't forget to change its permissions
(`400).

For Linux, Mac, and other *nix users, something like the following command would
be used to SSH into the `master`:

[source,role=copypaste]
----
ssh -i <path_to/qwikLABS-LXX-YYYY.pem> cloud-user@{{ MASTER_EXTERNAL_IP }}
----

Make sure that you use the correct path to your SSH key file.

NOTE: Windows users are encouraged to use the
link:https://www.chiark.greenend.org.uk/~sgtatham/putty/[PuTTY] client. Instructions for how
to use SSH keys with PuTTY can be found in their
link:https://the.earth.li/~sgtatham/putty/0.70/htmldoc/Chapter8.html#pubkey[documentation].

#### Look at the file
Use `cat`, `less`, or an editor to look at the `/etc/ansible/hosts` file:

[source]
----
cat /etc/ansible/hosts
----

General settings and other variable information is defined on lines within the
`[OSEv3:vars]` section. There are also various host groups defined for things
like *Masters* and *Nodes*.

For more details on how OpenShift uses Ansible for its installation, please
refer to the
link:https://docs.openshift.com/container-platform/3.5/install_config/install/advanced_install.html#configuring-ansible[advanced
installer's documentation].

### Installing OpenShift
Since we have pre-configured the installer for you, you can simply run it.

#### Run the Installer
Launching the advanced installation is as simple as executing the following
command:

[source]
----
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
----

This will take some time. You might want to go get a beverage or check your
email. Come back in about 7-10 minutes. We have pre-cached as much of the
content as possible to make the installation go quickly. 

A typical multi-host installation like this might take around an hour depending
on the speed of your internet connection. Disconnected installation options are
also available. Prerequisites and other information is all covered in the
documentation.

### Verifying the Installation
Once the installation process is complete, there are some basic tests you can
perform to ensure that it went successfully.

#### Check the Logs
The installer is quite verbose, and can be made even more verbose. If you know
anything about Ansible, the output should be familiar to you. In any case, so
long as there are no fatal-type errors and all hosts exit "OK", the odds are
good that the installation was succesful.

If you look in your terminal at the output of the installer, it should finish
with something that looks like the following:

[source]
----
PLAY RECAP ***********************************************************************************
infra.internal.aws.testdrive.openshift.com : ok=241  changed=53   unreachable=0    failed=0   
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
master.internal.aws.testdrive.openshift.com : ok=703  changed=157  unreachable=0    failed=0   
node01.internal.aws.testdrive.openshift.com : ok=238  changed=51   unreachable=0    failed=0   
node02.internal.aws.testdrive.openshift.com : ok=238  changed=51   unreachable=0    failed=0   
node03.internal.aws.testdrive.openshift.com : ok=238  changed=51   unreachable=0    failed=0  
----

You will notice zero failed tasks.

#### Look at the Nodes
As an administrator, most of your interaction with OpenShift will be from the
command line. The `oc` program is a command line interface that talks to the
OpenShift API. 

On the `master` host, after the installation, the `root` system account is
preconfigured to use a special "super administrator" account. It is vitally
important that you protect access to the `root` system account, or to remove
this preconfigured config. Otherwise, anyone who can `sudo` on the master has
super user privileges on the entire cluster.

Additionally, since we ran the installation as `cloud-user`, this account, too,
is preconfigured for cluster administrator access.

Execute the following command to see a list of the *Nodes* that OpenShift knows
about:

[source]
----
oc get nodes
----

The output should look something like the following:

[source]
----
NAME                          STATUS                     AGE
{{INFRA_INTERNAL_FQDN}}     Ready                      1m
{{MASTER_INTERNAL_FQDN}}    Ready,SchedulingDisabled   1m
{{NODE1_INTERNAL_FQDN}}    Ready                      1m
{{NODE2_INTERNAL_FQDN}}    Ready                      1m
{{NODE3_INTERNAL_FQDN}}    Ready                      1m
----

All of the systems listed in the `[nodes]` group in the `/etc/ansible/hosts`
file should be listed here.

The OpenShift *Master* is also a *Node* because it needs to participate in the
software defined network (SDN). By default, however, scheduling is disabled --
no workload will be run on masters.

#### Check the Web Console
OpenShift provides a web console for users, developers and application operators
to interact with the environment. There are not many cluster administrative
functions to perform through the web console. Some OpenShift components (like
the internal image registry) run as workload inside the OpenShift environment,
and you could see these things. However, we have not yet explored authentication
topics, so you have no cluster administrator "human" accounts yet.

Point your browser to {{WEB_CONSOLE_URL}} to verify that the web console is
available and responding.

WARNING: You will receive a self-signed certificate error in your browser. When
OpenShift is installed, by default, a CA and SSL certificates are generated for
all inter-component communication within OpenShift, including the web console.
It is possible to provide your own SSL certificates during the installation, and
more information can be found in the
link:https://docs.openshift.com/container-platform/3.5/install_config/install/advanced_install.html#advanced-install-custom-certificates[custom
certificates] section of the installation documentation.

