## Skipping Modules

While the Test Drive is designed to be an experience that is linear in nature,
it is possible to skip modules. Skipping modules requires that you perform
certain automation tasks that will actually "do" the exercise for you.

For example, if you wanted to skip user and group configuration, later labs
still rely on this being completed, so you must still make sure the steps have
been executed.

We provide automation of each module using Ansible playbooks that are located in
the `{{ CODE_CLONE_LOCATION }}/tests` folder.


.The Automation Playbooks
[options="header"]
|==============================================
| Module     | Playbook
|2. Installation and Verification| run-module-2-installation.yaml
|3. Application Management Basics| run-module-3-app-mgmt-basics.yaml
|4. Project Request Template, Quotas, Limits|run-module-4-template-quota-limits.yaml
|5. Using External Authentication Providers (LDAP)|run-module-5-ldap-groupsync.yaml
|6. Infrastructure Management Basics|run-module-6-infra-mgmt.yaml
|7. Container-native Storage|run-module-7-cns.yaml
|==============================================

Executing the skip module playbooks is trivial. They are self-contained
Ansible playbooks that are run from the `{{ CODE_CLONE_LOCATION }}/tests`
directory.

There is a constraint that if you want to skip across multiple modules, **you
need to skip all preceding modules in order**. For example, if you wanted to
skip to Module 5 (that is, skipping modules 2-4 as well), you would need to run the
following:

----
cd {{ CODE_CLONE_LOCATION }}/tests/
ansible-playbook run-module-2-installation.yaml
ansible-playbook run-module-3-app-mgmt-basics.yaml
ansible-playbook run-module-4-template-quota-limits.yaml
----

[WARNING]
====
Do not run playbooks without following above constraint of running them in order.
====

[IMPORTANT]
====
Do not run the playbooks twice. They are not quite idempotent yet.
====
