#!/bin/bash
idm=idm.`hostname -d`
domain=`hostname -d`
dc_values=`echo $domain | sed 's/\./,dc=/g' | sed 's/^/dc=/'`

echo "Swap values in inventory"
sed -i "s/<DC>/$dc_values/g" /etc/ansible/hosts
sed -i "s/IDM/$idm/g" /etc/ansible/hosts

echo "Inventory updated"
