#!/bin/bash
idm=idm.`hostname -d`


echo "Waiting for the IDM server to grab the ca..."

while true; do
    nc $idm 389 < /dev/null
    if [ $? -eq 0 ]; then
        break
    fi
    sleep 1
done

mkdir -p /etc/origin/master

ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q ec2-user@${idm} -i /home/ec2-user/.ssh/id_rsa "sudo cp /etc/ipa/ca.crt /tmp && sudo chmod 755 /tmp/ca.crt"
scp -i /home/ec2-user/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q  ec2-user@${idm}:/tmp/ca.crt /etc/origin/master/

echo "Certificate acquired"
