apiVersion: v1
stringData:
  rox_central_endpoint: "central.stackrox.svc.cluster.local:443"
  # The address:port tuple for StackRox Central (example - rox.stackrox.io:443)
  rox_api_token: "YOUR_API_TOKEN_HERE"
  # StackRox API token with CI permissions
  # Refer to https://help.stackrox.com/docs/use-the-api/#generate-an-access-token
kind: Secret
metadata:
  name: roxsecrets
  namespace: pipeline-demo
type: Opaque
